name: Bug Report
description: Report a clearly broken issue.
labels: ["needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        # Microbot bug report
  - type: textarea
    attributes:
      label: Bug description
      description: How did you find the bug? Any additional details that might help?
    validations:
      required: true
